# Generated by Django 4.2.16 on 2024-09-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_type_job_work_type_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('on_site', 'On-site'), ('hybrid', 'Hybrid')], max_length=20),
        ),
    ]
