# Generated by Django 4.2.16 on 2024-10-05 09:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_letter'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv'),
        ),
    ]
