# Generated by Django 4.2.16 on 2024-09-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(default='Fagelvagen 18, Tyreso', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='Mark', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_jobs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default='+37060478224', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
