# Generated by Django 4.2.16 on 2024-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_application_address_application_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('closed', 'Closed')], default='under_review', max_length=20),
        ),
    ]
