# Generated by Django 4.2.16 on 2024-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
