# Generated by Django 4.2.16 on 2024-10-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_application_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
